apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dialogflow-sendgrid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dialogflow-sendgrid
  template:
    metadata:
      labels:
        app: dialogflow-sendgrid
    spec:
      containers:
      - name: dialogflow-sendgrid
        image: docker.pkg.github.com/mishushakov/dialogflow-sendgrid/dialogflow-sendgrid
        env:
          - name: INBOX_HOST
            value: smtp.sendgrid.net
          - name: INBOX_USER
            value: apikey
          - name: INBOX_PASSWORD
            value: <your-user-password>
          - name: FALLBACK_LANG
            value: en
          - name: GATEWAY
            value: https://cloud.ushakov.co